language: node_js
node_js:
  - "6"
  - "8"

cache: yarn
after_success:
  - yarn add coveralls
  - yarn run coverage -- --reporter=text-lcov | ./node_modules/.bin/coveralls

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
